# DevOps Pipeline definition for the OFS Beta Backend Data Pipeline 

# The code branch that will trigger a build
trigger:
- release/*

# The pr from branches to be included or excluded to trigger build
pr: none

# Build Agent Resources
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.10'

# Build Process Tree
steps:

# Enforce Python Version (see above)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
  displayName: 'Use Python $(python.version)'

# Create a Python Virtual Environment and download required dependencies
- script: |
    python3 -m venv .venv
    source .venv/bin/activate
    pip3 install --upgrade pip
    pip3 install -r requirements.txt --pre
  displayName: 'Install Python Dependencies'

# Execute Python Tests
- script: |
    pip install pytest
    pytest -v
  displayName: 'pytest'

# Archive the Azure Python Function into a ZIP package for deployment
- task: ArchiveFiles@2
  displayName: "Archive Files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    replaceExistingArchive: true

# Publish the ZIP package
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    ArtifactName: 'drop'


